import React from "react";
import { Form } from "react-bootstrap";

const CityList = ({ setActiveCity }) => {
  const handleSelect = (e) => {
    setActiveCity(e.target.value);
  };
  return (
    <Form.Control
      as="select"
      id="quicksearch_City_list"
      type="list"
    //   style={{
    //     fontFamily: `Arial, sans-serif`,
    //     fontSize: `12px`,
    //     width: `150px`,
    //     padding: `4px`,
    //   }}
      onChange={handleSelect}
    >
      <option value="">- Select a City-</option>
      <option value="Any">Any</option>
      <option value="Advance">Advance</option>
      <option value="Albemarle">Albemarle</option>
      <option value="Alexander">Alexander</option>
      <option value="Alexis">Alexis</option>
      <option value="Almond">Almond</option>
      <option value="Anderson">Anderson</option>
      <option value="Ansonville">Ansonville</option>
      <option value="Arden">Arden</option>
      <option value="Asheboro">Asheboro</option>
      <option value="Asheville">Asheville</option>
      <option value="Badin">Badin</option>
      <option value="Badin Lake">Badin Lake</option>
      <option value="Bakersville">Bakersville</option>
      <option value="Balsam">Balsam</option>
      <option value="Balsam Grove">Balsam Grove</option>
      <option value="Banner Elk">Banner Elk</option>
      <option value="Barnardsville">Barnardsville</option>
      <option value="Bat Cave">Bat Cave</option>
      <option value="Beech Mountain">Beech Mountain</option>
      <option value="Belmont">Belmont</option>
      <option value="Bessemer City">Bessemer City</option>
      <option value="Bethune">Bethune</option>
      <option value="Biltmore Forest">Biltmore Forest</option>
      <option value="Biltmore Lake">Biltmore Lake</option>
      <option value="Biscoe">Biscoe</option>
      <option value="Black Mountain">Black Mountain</option>
      <option value="Blacksburg">Blacksburg</option>
      <option value="Blackstock">Blackstock</option>
      <option value="Blowing Rock">Blowing Rock</option>
      <option value="Blythewood">Blythewood</option>
      <option value="Boiling Springs">Boiling Springs</option>
      <option value="Boomer">Boomer</option>
      <option value="Boone">Boone</option>
      <option value="Boonville">Boonville</option>
      <option value="Bostic">Bostic</option>
      <option value="Brevard">Brevard</option>
      <option value="Bryson City">Bryson City</option>
      <option value="Burnsville">Burnsville</option>
      <option value="Camden">Camden</option>
      <option value="Campobello">Campobello</option>
      <option value="Candler">Candler</option>
      <option value="Candor">Candor</option>
      <option value="Canton">Canton</option>
      <option value="Casar">Casar</option>
      <option value="Cashiers">Cashiers</option>
      <option value="Cassatt">Cassatt</option>
      <option value="Catawba">Catawba</option>
      <option value="Cedar Mountain">Cedar Mountain</option>
      <option value="Chapel Hill">Chapel Hill</option>
      <option value="Charlotte">Charlotte</option>
      <option value="Cheraw">Cheraw</option>
      <option value="Cherokee">Cherokee</option>
      <option value="Cherryville">Cherryville</option>
      <option value="Chesnee">Chesnee</option>
      <option value="Chester">Chester</option>
      <option value="Chesterfield">Chesterfield</option>
      <option value="Chimney Rock">Chimney Rock</option>
      <option value="China Grove">China Grove</option>
      <option value="Claremont">Claremont</option>
      <option value="Clemmons">Clemmons</option>
      <option value="Cleveland">Cleveland</option>
      <option value="Clover">Clover</option>
      <option value="Clyde">Clyde</option>
      <option value="Collettsville">Collettsville</option>
      <option value="Columbia">Columbia</option>
      <option value="Columbus">Columbus</option>
      <option value="Concord">Concord</option>
      <option value="Connelly Springs">Connelly Springs</option>
      <option value="Conover">Conover</option>
      <option value="Cooleemee">Cooleemee</option>
      <option value="Cornelius">Cornelius</option>
      <option value="Cramerton">Cramerton</option>
      <option value="Crouse">Crouse</option>
      <option value="Cullowhee">Cullowhee</option>
      <option value="Dallas">Dallas</option>
      <option value="Davidson">Davidson</option>
      <option value="Deep Gap">Deep Gap</option>
      <option value="Denton">Denton</option>
      <option value="Denver">Denver</option>
      <option value="Dillsboro">Dillsboro</option>
      <option value="Dobson">Dobson</option>
      <option value="Drexel">Drexel</option>
      <option value="Durham">Durham</option>
      <option value="East Bend">East Bend</option>
      <option value="East Flat Rock">East Flat Rock</option>
      <option value="East Spencer">East Spencer</option>
      <option value="Edgemoor">Edgemoor</option>
      <option value="Edneyville">Edneyville</option>
      <option value="Elgin">Elgin</option>
      <option value="Elk Park">Elk Park</option>
      <option value="Elkin">Elkin</option>
      <option value="Ellenboro">Ellenboro</option>
      <option value="Ellerbe">Ellerbe</option>
      <option value="Etowah">Etowah</option>
      <option value="Fairview">Fairview</option>
      <option value="Faith">Faith</option>
      <option value="Fallston">Fallston</option>
      <option value="Fayetteville">Fayetteville</option>
      <option value="Ferguson">Ferguson</option>
      <option value="Flat Rock">Flat Rock</option>
      <option value="Fleetwood">Fleetwood</option>
      <option value="Fletcher">Fletcher</option>
      <option value="Forest City">Forest City</option>
      <option value="Fort Lawn">Fort Lawn</option>
      <option value="Fort Mill">Fort Mill</option>
      <option value="Franklin">Franklin</option>
      <option value="Gaffney">Gaffney</option>
      <option value="Gaston">Gaston</option>
      <option value="Gastonia">Gastonia</option>
      <option value="Gerton">Gerton</option>
      <option value="Gilbert">Gilbert</option>
      <option value="Glen Alpine">Glen Alpine</option>
      <option value="Glenville">Glenville</option>
      <option value="Gold Hill">Gold Hill</option>
      <option value="Granite Falls">Granite Falls</option>
      <option value="Granite Quarry">Granite Quarry</option>
      <option value="Grassy Creek">Grassy Creek</option>
      <option value="Great Falls">Great Falls</option>
      <option value="Green Mountain">Green Mountain</option>
      <option value="Greensboro">Greensboro</option>
      <option value="Greenville">Greenville</option>
      <option value="Grover">Grover</option>
      <option value="Hamlet">Hamlet</option>
      <option value="Hamptonville">Hamptonville</option>
      <option value="Harmony">Harmony</option>
      <option value="Harrisburg">Harrisburg</option>
      <option value="Hayesville">Hayesville</option>
      <option value="Hays">Hays</option>
      <option value="Heath Springs">Heath Springs</option>
      <option value="Hemby Bridge">Hemby Bridge</option>
      <option value="Hendersonville">Hendersonville</option>
      <option value="Hickory">Hickory</option>
      <option value="Hickory Grove">Hickory Grove</option>
      <option value="Hiddenite">Hiddenite</option>
      <option value="High Point">High Point</option>
      <option value="High Shoals">High Shoals</option>
      <option value="Highlands">Highlands</option>
      <option value="Hildebran">Hildebran</option>
      <option value="Horse Shoe">Horse Shoe</option>
      <option value="Hot Springs">Hot Springs</option>
      <option value="Hudson">Hudson</option>
      <option value="Huntersville">Huntersville</option>
      <option value="Indian Land">Indian Land</option>
      <option value="Indian Trail">Indian Trail</option>
      <option value="Inman">Inman</option>
      <option value="Iron Station">Iron Station</option>
      <option value="Ironton Township">Ironton Township</option>
      <option value="Jefferson">Jefferson</option>
      <option value="Jonesville">Jonesville</option>
      <option value="Kannapolis">Kannapolis</option>
      <option value="Kernersville">Kernersville</option>
      <option value="Kershaw">Kershaw</option>
      <option value="King">King</option>
      <option value="Kings Mountain">Kings Mountain</option>
      <option value="Lake Junaluska">Lake Junaluska</option>
      <option value="Lake Lure">Lake Lure</option>
      <option value="Lake Toxaway">Lake Toxaway</option>
      <option value="Lake Wylie">Lake Wylie</option>
      <option value="Lancaster">Lancaster</option>
      <option value="Landis">Landis</option>
      <option value="Landrum">Landrum</option>
      <option value="Lansing">Lansing</option>
      <option value="Laurel Park">Laurel Park</option>
      <option value="Laurel Springs">Laurel Springs</option>
      <option value="Laurinburg">Laurinburg</option>
      <option value="Lawndale">Lawndale</option>
      <option value="Leesville">Leesville</option>
      <option value="Leicester">Leicester</option>
      <option value="Lenoir">Lenoir</option>
      <option value="Lewisville">Lewisville</option>
      <option value="Lexington">Lexington</option>
      <option value="Liberty Hill">Liberty Hill</option>
      <option value="Lilesville">Lilesville</option>
      <option value="Lincolnton">Lincolnton</option>
      <option value="Linville">Linville</option>
      <option value="Linwood">Linwood</option>
      <option value="Little Switzerland">Little Switzerland</option>
      <option value="Locust">Locust</option>
      <option value="Loris">Loris</option>
      <option value="Lowell">Lowell</option>
      <option value="Lugoff">Lugoff</option>
      <option value="Maggie Valley">Maggie Valley</option>
      <option value="Maiden">Maiden</option>
      <option value="Marion">Marion</option>
      <option value="Mars Hill">Mars Hill</option>
      <option value="Marshall">Marshall</option>
      <option value="Marshville">Marshville</option>
      <option value="Marvin">Marvin</option>
      <option value="Matthews">Matthews</option>
      <option value="McAdenville">McAdenville</option>
      <option value="McConnells">McConnells</option>
      <option value="McGrady">McGrady</option>
      <option value="Mebane">Mebane</option>
      <option value="Midland">Midland</option>
      <option value="Mill Spring">Mill Spring</option>
      <option value="Millers Creek">Millers Creek</option>
      <option value="Mills River">Mills River</option>
      <option value="Mineral Springs">Mineral Springs</option>
      <option value="Mint Hill">Mint Hill</option>
      <option value="Misenheimer">Misenheimer</option>
      <option value="Mocksville">Mocksville</option>
      <option value="Monroe">Monroe</option>
      <option value="Montreat">Montreat</option>
      <option value="Mooresboro">Mooresboro</option>
      <option value="Mooresville">Mooresville</option>
      <option value="Moravian Falls">Moravian Falls</option>
      <option value="Morganton">Morganton</option>
      <option value="Morven">Morven</option>
      <option value="Mount Airy">Mount Airy</option>
      <option value="Mount Croghan">Mount Croghan</option>
      <option value="Mount Gilead">Mount Gilead</option>
      <option value="Mount Holly">Mount Holly</option>
      <option value="Mount Pleasant">Mount Pleasant</option>
      <option value="Mount Ulla">Mount Ulla</option>
      <option value="Mountain Home">Mountain Home</option>
      <option value="Mt Ulla">Mt Ulla</option>
      <option value="Murphy">Murphy</option>
      <option value="N Wilkesboro">N Wilkesboro</option>
      <option value="Nebo">Nebo</option>
      <option value="New London">New London</option>
      <option value="Newland">Newland</option>
      <option value="Newton">Newton</option>
      <option value="North Wilkesboro">North Wilkesboro</option>
      <option value="Norwood">Norwood</option>
      <option value="Oakboro">Oakboro</option>
      <option value="Ocean Isle">Ocean Isle</option>
      <option value="Old Fort">Old Fort</option>
      <option value="Olin">Olin</option>
      <option value="Pageland">Pageland</option>
      <option value="Patterson">Patterson</option>
      <option value="Peachland">Peachland</option>
      <option value="Penrose">Penrose</option>
      <option value="Pfafftown">Pfafftown</option>
      <option value="Pineville">Pineville</option>
      <option value="Pisgah Forest">Pisgah Forest</option>
      <option value="Polkton">Polkton</option>
      <option value="Purlear">Purlear</option>
      <option value="Qualla">Qualla</option>
      <option value="Raleigh">Raleigh</option>
      <option value="Ranlo">Ranlo</option>
      <option value="Rhodhiss">Rhodhiss</option>
      <option value="Richburg">Richburg</option>
      <option value="Richfield">Richfield</option>
      <option value="Robbinsville">Robbinsville</option>
      <option value="Rock Hill">Rock Hill</option>
      <option value="Rockingham">Rockingham</option>
      <option value="Rockwell">Rockwell</option>
      <option value="Ronda">Ronda</option>
      <option value="Rosman">Rosman</option>
      <option value="Ruby">Ruby</option>
      <option value="Rural Hall">Rural Hall</option>
      <option value="Rutherford College">Rutherford College</option>
      <option value="Rutherfordton">Rutherfordton</option>
      <option value="Salisbury">Salisbury</option>
      <option value="Saluda">Saluda</option>
      <option value="Sapphire">Sapphire</option>
      <option value="Sharon">Sharon</option>
      <option value="Shelby">Shelby</option>
      <option value="Sherrills Ford">Sherrills Ford</option>
      <option value="Siler City">Siler City</option>
      <option value="Smyrna">Smyrna</option>
      <option value="Spartanburg">Spartanburg</option>
      <option value="Spencer">Spencer</option>
      <option value="Spindale">Spindale</option>
      <option value="Spruce Pine">Spruce Pine</option>
      <option value="Stallings">Stallings</option>
      <option value="Stanfield">Stanfield</option>
      <option value="Stanley">Stanley</option>
      <option value="Star">Star</option>
      <option value="State Road">State Road</option>
      <option value="Statesville">Statesville</option>
      <option value="Stony Point">Stony Point</option>
      <option value="Sugar Grove">Sugar Grove</option>
      <option value="Sugar Mountain">Sugar Mountain</option>
      <option value="Sumter">Sumter</option>
      <option value="Swannanoa">Swannanoa</option>
      <option value="Sylva">Sylva</option>
      <option value="Taylorsville">Taylorsville</option>
      <option value="Tega Cay">Tega Cay</option>
      <option value="Terrell">Terrell</option>
      <option value="Thomasville">Thomasville</option>
      <option value="Thurmond">Thurmond</option>
      <option value="Todd">Todd</option>
      <option value="Topton">Topton</option>
      <option value="Traphill">Traphill</option>
      <option value="Travelers Rest">Travelers Rest</option>
      <option value="Troutman">Troutman</option>
      <option value="Troy">Troy</option>
      <option value="Tryon">Tryon</option>
      <option value="Tuckasegee">Tuckasegee</option>
      <option value="Union">Union</option>
      <option value="Union Grove">Union Grove</option>
      <option value="Union Mills">Union Mills</option>
      <option value="Valdese">Valdese</option>
      <option value="Vale">Vale</option>
      <option value="Van Wyck">Van Wyck</option>
      <option value="Vilas">Vilas</option>
      <option value="Waco">Waco</option>
      <option value="Wadesboro">Wadesboro</option>
      <option value="Waxhaw">Waxhaw</option>
      <option value="Waynesville">Waynesville</option>
      <option value="Weaverville">Weaverville</option>
      <option value="Webster">Webster</option>
      <option value="Weddington">Weddington</option>
      <option value="Wellford">Wellford</option>
      <option value="Wesley Chapel">Wesley Chapel</option>
      <option value="West Jefferson">West Jefferson</option>
      <option value="Whittier">Whittier</option>
      <option value="Wilkesboro">Wilkesboro</option>
      <option value="Wilmington">Wilmington</option>
      <option value="Wingate">Wingate</option>
      <option value="Winnsboro">Winnsboro</option>
      <option value="Winston Salem">Winston Salem</option>
      <option value="Woodfin">Woodfin</option>
      <option value="Woodleaf">Woodleaf</option>
      <option value="Yadkinville">Yadkinville</option>
      <option value="York">York</option>
      <option value="Zirconia">Zirconia</option>
    </Form.Control>
  );
};

export default CityList;
